# roles/ws-base/tasks/main.yml
- name: Run the equivalent of "pacman -Syu"
  tags: always
  community.general.pacman:
    update_cache: true
    upgrade: true
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Archlinux"

- name: Run the equivalent of "apt-get update" and "apt-get dist-upgrade" and "apt-get upgrade"
  tags: always
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Run the equivalent of "dnf upgrade"
  tags: always
  ansible.builtin.dnf5:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Autoremove unneeded Debian packages
  tags: always
  ansible.builtin.apt:
    autoremove: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Autoremove unneeded RedHat packages
  ansible.builtin.dnf5:
    autoremove: yes
  when: ansible_facts['os_family'] == "RedHat"
