# roles/ws-base/vars/main.yml
base_packages:
  Archlinux:
    - htop
    - tmux
    - openssh
    - git
    - make
    - unzip
    - base-devel
    - ripgrep
    - xclip
    - curl
    - lua51
    - fd
  Debian:
    - htop
    - tmux
    - openssh-client
    - git
    - make
    - unzip
    - build-essential
    - ripgrep
    - xclip
    - curl
    - lua5.1
    - liblua5.1-0-dev
    - software-properties-common
    - fd-find
  RedHat:
    - htop
    - tmux
    - openssh
    - git
    - make
    - unzip
    - '@Development tools'
    - ripgrep
    - xclip
    - curl
    - lua51
    - lua51-devel
    - fd-find
