---
# Neovim setup - distro-specific

# == Debian (stable) ==
- name: Install dev tools and dependencies on Debian
  ansible.builtin.apt:
    update_cache: yes
    name:
      - make
      - gcc
      - ripgrep
      - unzip
      - git
      - xclip
      - curl
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Download latest Neovim release on Debian
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
    dest: /tmp/nvim-linux-x86_64.tar.gz
    mode: '0644'
  when: ansible_facts['os_family'] == "Debian"

- name: Remove existing Neovim directory
  file:
    path: /opt/nvim
    state: absent

- name: Extract and install Neovim binary to /opt on Debian
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux-x86_64.tar.gz
    dest: /opt
    remote_src: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Symlink Neovim binary to /usr/local/bin
  ansible.builtin.file:
    src: /opt/nvim-linux64/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
    force: true
  when: ansible_facts['distribution'] == "Debian"

# == Fedora ==
- name: Install Neovim and dependencies on Fedora
  ansible.builtin.dnf:
    name:
      - gcc
      - make
      - git
      - ripgrep
      - fd-find
      - unzip
      - neovim
    state: present
  when: ansible_facts['distribution'] == "Fedora"

# == Arch Linux ==
- name: Install Neovim and dependencies on Arch
  community.general.pacman:
    name:
      - gcc
      - make
      - git
      - ripgrep
      - fd
      - unzip
      - neovim
    state: present
    update_cache: true
  when: ansible_facts['os_family'] == "Archlinux"

# == Neovim Kickstart ==
- name: Ensure Neovim config directory exists
  ansible.builtin.file:
    path: "/home/michael/.config/nvim"
    state: directory
    mode: '0755'

- name: Clone kickstart.nvim into Neovim config
  ansible.builtin.git:
    repo: https://github.com/MichaelSandilands/kickstart.nvim.git
    dest: "/home/michael/.config/nvim"
    version: HEAD
    update: yes
